[mongo]
mongo1 ansible_host=PUBLIC_IP_NODE_1 mongo_private_ip=10.0.0.3
mongo2 ansible_host=PUBLIC_IP_NODE_2 mongo_private_ip=10.0.0.2
mongo3 ansible_host=PUBLIC_IP_NODE_3 mongo_private_ip=10.0.0.4

[mongo:vars]
ansible_user=root
ansible_port=22
ansible_connection=ssh
